apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: demonstrate-envars
spec:
  containers:
    - name: nginx      
      env:
        - name: DEMO_GREETING
          value: "Hello from the environment"
        - name: DEMO_FAREWELL
          value: "Such a sweet sorrow"
